name: coverage_stats

on:
  pull_request:
    types: synchronize

jobs:
  coverage_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - run: go version
      - name: build coverage
        run: |
          sh ./scripts/coverage/coverage.sh ${{ github.head_ref }} ${{ github.base_ref }}
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage.md
          recreate: true
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat coverage_d.md | reviewdog -efm="%f:%l.%c: %m" -diff="git diff origin/${{ github.base_ref }}" -reporter=github-pr-review
